# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
cache: cocoapods
podfile: Example/Podfile
env:
  global:
    - LC_CTYPE=en.US.UTF-8
    - LANG=en_US.UTF_8
  matrix:
      - DESTINATION="OS=8.3,name=iPhone 6 Plus" SCHEME="Operative-Example" SDK=iphonesimulator8.3 BUILD_EXAMPLE="YES" POD_LINT="YES"
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install --project-directory=Example
install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - if [ $BUILD_EXAMPLE == "YES" ]; then 
    xcodebuild -workspace "Example/Operative.xcworkspace" -scheme "Operative-Example" -sdk "$SDK" -destination "$DESTINATION" 
      -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c; 
    fi
  - if [ $BUILD_EXAMPLE == "YES" ]; then 
    xcodebuild -workspace "Example/Operative.xcworkspace" -scheme "Operative-Example" -sdk "$SDK" -destination "$DESTINATION" 
      -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c; 
    fi
  - if [ $POD_LINT == "YES" ]; then 
      pod lib lint --quick; 
    fi
